name: Build RSS (hourly)

on:
  schedule:
    - cron: "0 * * * *"   # co pełną godzinę (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Build feed.xml
        run: python scraper.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add feed.xml
            git commit -m "Update feed.xml"
            git push
          else:
            echo "No changes."
          fi
